language: java
env:
 - secure: "SZTdJkWTjP9sPAkakxs283Dg9h732/PF4dJVvYAwEB5sL6fqOVej77/zt92GkQ+cVWyopfsWxw9pHVEcQq6kEXYSGl3IdwJWsOA3v1YTDFwoRenSWjrGpkWt9AdN3gfQOJ/TXPvZAZYUk0c1wDV56qQYv0P+jMnMCJNISrCPa3g="
before_install:
 - if [[ "${TRAVIS_SECURE_ENV_VARS}" == "true" ]]; then echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"><servers><server><id>repo-daboross-net</id><username>'${REPO_USERNAME}'</username><password>'${REPO_PASSWORD}'</password></server></servers></settings>' > ${HOME}/.m2/settings.xml; fi
install:
 - mvn --fail-never clean package
script:
 - mvn clean package
after_success:
 - if [[ "${TRAVIS_SECURE_ENV_VARS}" ]]; then mvn deploy; fi
