language: java
env:
 - secure: "SZTdJkWTjP9sPAkakxs283Dg9h732/PF4dJVvYAwEB5sL6fqOVej77/zt92GkQ+cVWyopfsWxw9pHVEcQq6kEXYSGl3IdwJWsOA3v1YTDFwoRenSWjrGpkWt9AdN3gfQOJ/TXPvZAZYUk0c1wDV56qQYv0P+jMnMCJNISrCPa3g="
before_install:
 - |
  if [[ "${TRAVIS_SECURE_ENV_VARS}" == "true" ]]; then
  export KNOWN_HOST_SSH='|1|wPcvQE9BDavFe6leYQATAMurskE=|LZirQZaAuhFUCCw+J7Q/pedeTho= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzp6eC7j6+XncNqkPwH+s+lYrf01fOjFLhgctRtkAvJsdBui8Q4ys3fMG/6wvQovdjrqVoLL61J6feXhEZqPdJMETsOkbG6XTOSOb1HCZ1rK7rC++RRhgrINDQWl/aXrmcHkM6iIXsffmrAX8iswzNJjcZDCKKri04hYFQ84upWg+icUcAJqSJt9/LF+zvR1Cq64c5EFY1WOYScC83qhfNg1unZU1XVRiFir9+9rDdW5u0MPhE4hm9IWXD2/cbIFdUHQUXyTSS6GPmEyBhE7fuVa7Zw7g17jUNSqFgrRd29TmT793Mul90nPCGQqiXnFfRj7dvOYJpf1PmTZLiRICT';
  export MVN_SETTINGS_XML='<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"><servers><server><id>repo-daboross-net</id><username>'"${REPO_USERNAME}"'</username><password>'"${REPO_PASSWORD}"'</password></server></servers></settings>';
  mkdir -p "${HOME}/.m2/"
  echo "${MVN_SETTINGS_XML}" > "${HOME}/.m2/settings.xml";
  mkdir -p "${HOME}/.ssh";
  chmod 700 "${HOME}/.ssh";
  echo "${KNOWN_HOST_SSH}" > "${HOME}/.ssh/known_hosts";
  fi
install:
 - mvn --fail-never clean package
script:
 - mvn clean package
after_success:
 - if [[ "${TRAVIS_SECURE_ENV_VARS}" ]]; then cat "${HOME}/.ssh/known_hosts"; mvn deploy; fi
